### ISSUE TITLE
JAAS Example is not working on Wildfly 26.1.3

### ISSUE THREAD

**Issue by eliabrio** [wildfly-security-incubator/elytron-examples#164]
JAAS example is not wokring on Wildfly 26.1.3. 

The failure is being thrown when executing:

```
[standalone@localhost:9990 /] /subsystem=undertow/application-security-domain=other:write-attribute(name=http-authentication-factory,value=example-loginconfig-http-auth)
```

Output
```
{
    "outcome" => "failed",
    "failure-description" => "WFLYCTL0105: security-domain is invalid in combination with http-authentication-factory",
    "rolled-back" => true
}
```

**Comment by cam-rod** [comment]
Hey, I just tested this and it seems to be working properly from the CLI script. If you're manually entering the commands into the CLI, the security domain needs to be removed at the same time as the authentication factory is added. It's the only part of the script that requires `batch`, so you should be able to enter these commands one by one without issue:

```
batch
/subsystem=undertow/application-security-domain=other:write-attribute(name=http-authentication-factory,value=example-loginconfig-http-auth)
/subsystem=undertow/application-security-domain=other:undefine-attribute(name=security-domain)
run-batch
```

You can learn more about the batch commands in the [WildFly Admin Guide](https://docs.wildfly.org/27/Admin_Guide.html#batch-processing).

**Comment by eliabrio** [comment]
@cam-rod thanks for your response! When running this commands one by one it does not work, and throw the error. But I see why those two commands should run in a batch, and it worked for me.
Would be nice to add some notice \ warning about this. 

Anyway thanks a lot!!
